version: '3.7'

services:
  postgres:
    container_name: baskin-micorservice-product
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ./sql/nanoid.sql:/docker-entrypoint-initdb.d/2.nanoid.sql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/3.schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/4.data.sql
